apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: qc-extra-alerts
  labels: { release: prometheus }
spec:
  groups:
    - name: qc-webhook-latency
      rules:
        - alert: QcWebhookHighLatencyP95
          expr: histogram_quantile(0.95, sum by (le) (rate(qc_webhook_processing_seconds_bucket[10m]))) > 2
          for: 10m
          labels: { severity: ticket }
          annotations:
            summary: "Webhook p95 > 2s"
            description: "Investigate DB/Redis and signature checks."
    - name: qc-acquirer
      rules:
        - alert: QcAcquirerTimeouts
          expr: increase(qc_acquirer_timeouts_total[10m]) > 10
          for: 10m
          labels: { severity: page }
          annotations:
            summary: "Acquirer timeouts spiked"
            description: "Upstream gateway issues or network egress blocked."
    - name: qc-redis
      rules:
        - alert: QcRedisErrors
          expr: increase(redis_errors_total[10m]) > 0
          for: 5m
          labels: { severity: ticket }
          annotations:
            summary: "Redis errors detected"
            description: "Check Redis availability and network policies."
