version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: qatarchash
    volumes: [ "pg:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d qatarchash"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/qatarchash
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_BASE_URL=https://your-backend-domain
      - ALLOWED_ORIGINS=https://your-dashboard-domain
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    ports: [ "3001:3001" ]

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.prod
    environment:
      - NEXT_PUBLIC_API_BASE=https://your-backend-domain
    depends_on:
      - backend
    ports: [ "3000:3000" ]

volumes:
  pg: {}
