openapi: 3.0.3
info:
  title: QatarCash API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Admin login (JWT)
  /api/payment-links:
    post:
      summary: Create payment link
  /api/status/{token}:
    get:
      summary: Get payment status
  /admin/payment-links:
    get:
      summary: List payment links (admin)
