apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qc-backend-np
spec:
  podSelector:
    matchLabels:
      app: qc-backend
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    - to:
        - ipBlock: { cidr: 0.0.0.0/0 }
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.redisNamespace }}
      ports:
        - protocol: TCP
          port: 6379
