apiVersion: apps/v1
kind: Deployment
metadata: { name: qc-backend }
spec:
  replicas: 2
  selector: { matchLabels: { app: qc-backend } }
  template:
    metadata: { labels: { app: qc-backend } }
    spec:
      containers:
        - name: app
          image: your-registry/qc-backend:latest
          env:
            - { name: DATABASE_URL, value: "postgresql://user:pass@pg:5432/qatarchash" }
            - { name: JWT_SECRET, valueFrom: { secretKeyRef: { name: qc-secrets, key: JWT_SECRET } } }
            - { name: WEBHOOK_SECRET, valueFrom: { secretKeyRef: { name: qc-secrets, key: WEBHOOK_SECRET } } }
            - { name: PUBLIC_BASE_URL, value: "https://your-backend-domain" }
            - { name: ALLOWED_ORIGINS, value: "https://your-dashboard-domain" }
          ports: [ { containerPort: 3001 } ]
---
apiVersion: v1
kind: Service
metadata: { name: qc-backend }
spec:
  selector: { app: qc-backend }
  ports: [ { port: 80, targetPort: 3001 } ]
