apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: pg-pvc }
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: pg }
spec:
  replicas: 1
  selector: { matchLabels: { app: pg } }
  template:
    metadata: { labels: { app: pg } }
    spec:
      containers:
        - name: pg
          image: postgres:16-alpine
          env:
            - { name: POSTGRES_USER, value: "user" }
            - { name: POSTGRES_PASSWORD, value: "pass" }
            - { name: POSTGRES_DB, value: "qatarchash" }
          ports: [ { containerPort: 5432 } ]
          volumeMounts: [ { name: data, mountPath: /var/lib/postgresql/data } ]
      volumes: [ { name: data, persistentVolumeClaim: { claimName: pg-pvc } } ]
---
apiVersion: v1
kind: Service
metadata: { name: pg }
spec:
  selector: { app: pg }
  ports: [ { port: 5432, targetPort: 5432 } ]
