name: Backend Docker → GHCR
on:
  push:
    branches: [ main ]
    paths: [ 'backend/**', '.github/workflows/backend-ghcr.yml' ]
  workflow_dispatch:
permissions: { contents: read, packages: write }
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest
